${PULP_DIR}/common_cells/src/ecc_pkg.sv
${PULP_DIR}/common_cells/src/cf_math_pkg.sv
${PULP_DIR}/fpnew/src/fpnew_pkg.sv
${PULP_DIR}/common_cells/include/common_cells/assertions.svh
${PULP_DIR}/common_cells/include/common_cells/registers.svh
${PULP_DIR}/fpnew/src/fpnew_classifier.sv
${PULP_DIR}/fpnew/src/fpnew_rounding.sv
${PULP_DIR}/common_cells/src/binary_to_gray.sv
${PULP_DIR}/common_cells/src/deprecated/fifo_v2.sv
${PULP_DIR}/common_cells/src/id_queue.sv
${PULP_DIR}/common_cells/src/fall_through_register.sv
${PULP_DIR}/common_cells/src/sync_wedge.sv
${PULP_DIR}/common_cells/src/edge_propagator.sv
${PULP_DIR}/common_cells/src/stream_to_mem.sv
${PULP_DIR}/common_cells/src/edge_propagator_rx.sv
${PULP_DIR}/common_cells/src/max_counter.sv
${PULP_DIR}/common_cells/src/lfsr_8bit.sv
${PULP_DIR}/common_cells/src/lfsr.sv
${PULP_DIR}/common_cells/src/ecc_decode.sv
${PULP_DIR}/common_cells/src/stream_fork.sv
${PULP_DIR}/common_cells/src/lzc.sv
${PULP_DIR}/common_cells/src/stream_filter.sv
${PULP_DIR}/common_cells/src/fifo_v3.sv
${PULP_DIR}/common_cells/src/popcount.sv
${PULP_DIR}/common_cells/src/edge_propagator_tx.sv
${PULP_DIR}/common_cells/src/edge_detect.sv
${PULP_DIR}/common_cells/src/stream_fifo.sv
${PULP_DIR}/common_cells/src/stream_join.sv
${PULP_DIR}/common_cells/src/stream_arbiter_flushable.sv
${PULP_DIR}/common_cells/src/stream_arbiter.sv
${PULP_DIR}/common_cells/src/sync.sv
${PULP_DIR}/common_cells/src/lfsr_16bit.sv
${PULP_DIR}/common_cells/src/delta_counter.sv
${PULP_DIR}/common_cells/src/mv_filter.sv
${PULP_DIR}/common_cells/src/plru_tree.sv
${PULP_DIR}/common_cells/src/addr_decode.sv
${PULP_DIR}/common_cells/src/cdc_fifo_gray.sv
${PULP_DIR}/common_cells/src/stream_demux.sv
${PULP_DIR}/common_cells/src/isochronous_spill_register.sv
${PULP_DIR}/common_cells/src/exp_backoff.sv
${PULP_DIR}/common_cells/src/stream_xbar.sv
${PULP_DIR}/common_cells/src/rstgen_bypass.sv
${PULP_DIR}/common_cells/src/onehot_to_bin.sv
${PULP_DIR}/common_cells/src/stream_fork_dynamic.sv
${PULP_DIR}/common_cells/src/stream_mux.sv
${PULP_DIR}/common_cells/src/gray_to_binary.sv
${PULP_DIR}/common_cells/src/stream_intf.sv
${PULP_DIR}/common_cells/src/sub_per_hash.sv
${PULP_DIR}/common_cells/src/stream_register.sv
${PULP_DIR}/common_cells/src/rr_arb_tree.sv
${PULP_DIR}/common_cells/src/cdc_2phase.sv
${PULP_DIR}/common_cells/src/counter.sv
${PULP_DIR}/common_cells/src/spill_register_flushable.sv
${PULP_DIR}/common_cells/src/spill_register.sv
${PULP_DIR}/common_cells/src/serial_deglitch.sv
${PULP_DIR}/common_cells/src/stream_delay.sv
${PULP_DIR}/common_cells/src/stream_omega_net.sv
${PULP_DIR}/common_cells/src/rstgen.sv
${PULP_DIR}/common_cells/src/unread.sv
${PULP_DIR}/common_cells/src/shift_reg.sv
${PULP_DIR}/common_cells/src/cdc_fifo_2phase.sv
${PULP_DIR}/axi/include/axi/typedef.svh
${PULP_DIR}/axi/include/axi/assign.svh
${PULP_DIR}/axi/src/axi_serializer.sv
${PULP_DIR}/axi/src/axi_err_slv.sv
${PULP_DIR}/axi/src/axi_demux.sv
${PULP_DIR}/axi/src/axi_demux_simple.sv
${PULP_DIR}/axi/src/axi_cut.sv
${PULP_DIR}/axi/src/axi_lite_join.sv
${PULP_DIR}/axi/src/axi_xbar.sv
${PULP_DIR}/axi/src/axi_intf.sv
${PULP_DIR}/axi/src/axi_lite_demux.sv
${PULP_DIR}/axi/src/axi_lite_mailbox.sv
${PULP_DIR}/axi/src/axi_mux.sv
${PULP_DIR}/axi/src/axi_atop_filter.sv
${PULP_DIR}/axi/src/axi_join.sv
${PULP_DIR}/axi/src/axi_isolate.sv
${PULP_DIR}/axi/src/axi_cdc_dst.sv
${PULP_DIR}/axi/src/axi_iw_converter.sv
${PULP_DIR}/axi/src/axi_id_prepend.sv
${PULP_DIR}/axi/src/axi_delayer.sv
${PULP_DIR}/axi/src/axi_lite_dw_converter.sv
${PULP_DIR}/axi/src/axi_cdc.sv
${PULP_DIR}/axi/src/axi_lite_to_axi.sv
${PULP_DIR}/axi/src/axi_cdc_src.sv
${PULP_DIR}/axi/src/axi_modify_address.sv
${PULP_DIR}/axi/src/axi_multicut.sv
${PULP_DIR}/axi/src/axi_lite_regs.sv
${PULP_DIR}/axi/src/axi_to_axi_lite.sv
${PULP_DIR}/axi/src/axi_burst_splitter.sv
${PULP_DIR}/axi/src/axi_lite_xbar.sv
${PULP_DIR}/axi/src/axi_lite_mux.sv
${PULP_DIR}/axi/src/axi_id_remap.sv
${PULP_DIR}/axi/src/axi_id_serialize.sv
${PULP_DIR}/axi/src/axi_lite_to_apb.sv
${RTL_DIR}/src/sauria_addr_pkg.sv
${RTL_DIR}/src/df_controller/df_controller_pkg.sv
${RTL_DIR}/src/df_controller/interfaces.sv
${RTL_DIR}/src/df_controller/acc_ready_queue.sv
${RTL_DIR}/src/df_controller/df_controller_top.sv
${RTL_DIR}/src/df_controller/sauria_dma_controller.sv
${RTL_DIR}/src/df_controller/sauria_dma_pointer_generator.sv
${RTL_DIR}/src/df_controller/sauria_interface.sv
${RTL_DIR}/src/dma/dma_top.sv
${RTL_DIR}/src/dma/redma/src/r_engine.sv
${RTL_DIR}/src/dma/redma/src/aw_engine.sv
${RTL_DIR}/src/dma/redma/src/transaction_generator.sv
${RTL_DIR}/src/dma/redma/src/redma_pkg.sv
${RTL_DIR}/src/dma/redma/src/ar_engine.sv
${RTL_DIR}/src/dma/redma/src/realigner.sv
${RTL_DIR}/src/dma/redma/src/data_fifo.sv
${RTL_DIR}/src/dma/redma/src/b_engine.sv
${RTL_DIR}/src/dma/redma/src/conf_regs.sv
${RTL_DIR}/src/dma/redma/src/redma_top.sv
${RTL_DIR}/src/dma/redma/src/w_engine.sv
${RTL_DIR}/src/axi/axi_lite_2ram.sv
${RTL_DIR}/src/axi/axi_full_2ram.sv
${RTL_DIR}/src/axi/axi_mem_slave.sv
${RTL_DIR}/src/axi/axi_lite_err_slv_intf.sv
${RTL_DIR}/src/common/cdc_sync_reg.sv
${RTL_DIR}/src/common/cnt_dualctx.sv
${RTL_DIR}/src/common/fifo_memory_ff.sv
${RTL_DIR}/src/common/cnt_generic.sv
${RTL_DIR}/src/sauria_core/config/config_regs.sv
${RTL_DIR}/src/sauria_core/control/context_switch_controller.sv
${RTL_DIR}/src/sauria_core/control/context_fsm.sv
${RTL_DIR}/src/sauria_core/control/feeders_fsm.sv
${RTL_DIR}/src/sauria_core/control/main_controller.sv
${RTL_DIR}/src/sauria_core/data_feeder/feed_data_manager.sv
${RTL_DIR}/src/sauria_core/data_feeder/feed_xy_lane.sv
${RTL_DIR}/src/sauria_core/data_feeder/wei_feeder.sv
${RTL_DIR}/src/sauria_core/data_feeder/feed_registers.sv
${RTL_DIR}/src/sauria_core/data_feeder/ifmap_feeder.sv
${RTL_DIR}/src/sauria_core/data_feeder/wei_idxcnt.sv
${RTL_DIR}/src/sauria_core/data_feeder/ifmap_idxcnt.sv
${RTL_DIR}/src/sauria_core/psm/psm_wdata_manager.sv
${RTL_DIR}/src/sauria_core/psm/psm_idxcnt.sv
${RTL_DIR}/src/sauria_core/psm/psm_rdata_manager.sv
${RTL_DIR}/src/sauria_core/psm/psm_shift_register.sv
${RTL_DIR}/src/sauria_core/psm/psm_shift_fsm.sv
${RTL_DIR}/src/sauria_core/psm/psm_top.sv
${RTL_DIR}/src/sauria_core/sram/sram_top.sv
${RTL_DIR}/src/sauria_core/sram/ram_inferred.sv
${RTL_DIR}/src/sauria_core/sram/ram_intf_wrapper.sv
${RTL_DIR}/src/sauria_core/systolic_array/sa_array.sv
${RTL_DIR}/src/sauria_core/systolic_array/zero_det_neg.sv
${RTL_DIR}/src/sauria_core/systolic_array/sa_processing_element.sv
${RTL_DIR}/src/sauria_core/systolic_array/adder/adder_truah.sv
${RTL_DIR}/src/sauria_core/systolic_array/adder/adder_trua.sv
${RTL_DIR}/src/sauria_core/systolic_array/adder/adder_gear.sv
${RTL_DIR}/src/sauria_core/systolic_array/adder/adder_ideal.sv
${RTL_DIR}/src/sauria_core/systolic_array/adder/adder_generic.sv
${RTL_DIR}/src/sauria_core/systolic_array/adder/adder_gear_2c.sv
${RTL_DIR}/src/sauria_core/systolic_array/adder/adder_loa.sv
${RTL_DIR}/src/sauria_core/systolic_array/multiplier/multiplier_booth.sv
${RTL_DIR}/src/sauria_core/systolic_array/multiplier/wallace_8.sv
${RTL_DIR}/src/sauria_core/systolic_array/multiplier/multiplier_bam.sv
${RTL_DIR}/src/sauria_core/systolic_array/multiplier/multiplier_ideal.sv
${RTL_DIR}/src/sauria_core/systolic_array/multiplier/multiplier_log.sv
${RTL_DIR}/src/sauria_core/systolic_array/multiplier/lopd.sv
${RTL_DIR}/src/sauria_core/systolic_array/multiplier/wallace_4.sv
${RTL_DIR}/src/sauria_core/systolic_array/multiplier/multiplier_wallace.sv
${RTL_DIR}/src/sauria_core/systolic_array/multiplier/wallace_16.sv
${RTL_DIR}/src/sauria_core/systolic_array/multiplier/mul_2x2.sv
${RTL_DIR}/src/sauria_core/systolic_array/multiplier/bam_cell.sv
${RTL_DIR}/src/sauria_core/systolic_array/multiplier/multiplier_generic.sv
${RTL_DIR}/src/sauria_core/systolic_array/pulp_fma/fma_wrapper.sv
${RTL_DIR}/src/sauria_core/systolic_array/pulp_fma/fpnew_fma.sv
${RTL_DIR}/src/sauria_core/sauria_logic.sv
${RTL_DIR}/src/sauria_core/sauria_core.sv
${RTL_DIR}/src/sauria_subsystem.sv